/**
 * AI Mastering API
 * This is a AI Mastering API document. You can use the mastering feature of [AI Mastering](https://aimastering.com) through this API.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@bakuage.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ExternalSearchResultItunes', 'model/ExternalSearchResultYoutube'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ExternalSearchResultItunes'), require('./ExternalSearchResultYoutube'));
  } else {
    // Browser globals (root is window)
    if (!root.Aimastering) {
      root.Aimastering = {};
    }
    root.Aimastering.ExternalSearchResult = factory(root.Aimastering.ApiClient, root.Aimastering.ExternalSearchResultItunes, root.Aimastering.ExternalSearchResultYoutube);
  }
}(this, function(ApiClient, ExternalSearchResultItunes, ExternalSearchResultYoutube) {
  'use strict';




  /**
   * The ExternalSearchResult model module.
   * @module model/ExternalSearchResult
   * @version 1.1.0
   */

  /**
   * Constructs a new <code>ExternalSearchResult</code>.
   * @alias module:model/ExternalSearchResult
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>ExternalSearchResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ExternalSearchResult} obj Optional instance to populate.
   * @return {module:model/ExternalSearchResult} The populated <code>ExternalSearchResult</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('itunes')) {
        obj['itunes'] = ApiClient.convertToType(data['itunes'], [ExternalSearchResultItunes]);
      }
      if (data.hasOwnProperty('youtube')) {
        obj['youtube'] = ApiClient.convertToType(data['youtube'], [ExternalSearchResultYoutube]);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/ExternalSearchResultItunes>} itunes
   */
  exports.prototype['itunes'] = undefined;
  /**
   * @member {Array.<module:model/ExternalSearchResultYoutube>} youtube
   */
  exports.prototype['youtube'] = undefined;



  return exports;
}));


