/**
 * AI Mastering API
 * This is a AI Mastering API document. You can use the mastering feature of [AI Mastering](https://aimastering.com) through this API.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@bakuage.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Aimastering) {
      root.Aimastering = {};
    }
    root.Aimastering.ExternalSearchResultYoutube = factory(root.Aimastering.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ExternalSearchResultYoutube model module.
   * @module model/ExternalSearchResultYoutube
   * @version 1.1.0
   */

  /**
   * Constructs a new <code>ExternalSearchResultYoutube</code>.
   * @alias module:model/ExternalSearchResultYoutube
   * @class
   */
  var exports = function() {
    var _this = this;









  };

  /**
   * Constructs a <code>ExternalSearchResultYoutube</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ExternalSearchResultYoutube} obj Optional instance to populate.
   * @return {module:model/ExternalSearchResultYoutube} The populated <code>ExternalSearchResultYoutube</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
      if (data.hasOwnProperty('url')) {
        obj['url'] = ApiClient.convertToType(data['url'], 'String');
      }
      if (data.hasOwnProperty('thumbnail_url')) {
        obj['thumbnail_url'] = ApiClient.convertToType(data['thumbnail_url'], 'String');
      }
      if (data.hasOwnProperty('channel_id')) {
        obj['channel_id'] = ApiClient.convertToType(data['channel_id'], 'String');
      }
      if (data.hasOwnProperty('channel_url')) {
        obj['channel_url'] = ApiClient.convertToType(data['channel_url'], 'String');
      }
      if (data.hasOwnProperty('channel_name')) {
        obj['channel_name'] = ApiClient.convertToType(data['channel_name'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {String} description
   */
  exports.prototype['description'] = undefined;
  /**
   * @member {String} url
   */
  exports.prototype['url'] = undefined;
  /**
   * @member {String} thumbnail_url
   */
  exports.prototype['thumbnail_url'] = undefined;
  /**
   * @member {String} channel_id
   */
  exports.prototype['channel_id'] = undefined;
  /**
   * @member {String} channel_url
   */
  exports.prototype['channel_url'] = undefined;
  /**
   * @member {String} channel_name
   */
  exports.prototype['channel_name'] = undefined;



  return exports;
}));


