/**
 * AI Mastering API
 * This is a AI Mastering API document. You can use the mastering feature of [AI Mastering](https://aimastering.com) through this API.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: aimasteringcom@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Aimastering) {
      root.Aimastering = {};
    }
    root.Aimastering.LibraryAudioLike = factory(root.Aimastering.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The LibraryAudioLike model module.
   * @module model/LibraryAudioLike
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>LibraryAudioLike</code>.
   * @alias module:model/LibraryAudioLike
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>LibraryAudioLike</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LibraryAudioLike} obj Optional instance to populate.
   * @return {module:model/LibraryAudioLike} The populated <code>LibraryAudioLike</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('library_audio_id')) {
        obj['library_audio_id'] = ApiClient.convertToType(data['library_audio_id'], 'Number');
      }
      if (data.hasOwnProperty('user_id')) {
        obj['user_id'] = ApiClient.convertToType(data['user_id'], 'Number');
      }
    }
    return obj;
  }

  /**
   * Audio analysis id
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * Audio id
   * @member {Number} library_audio_id
   */
  exports.prototype['library_audio_id'] = undefined;
  /**
   * User id
   * @member {Number} user_id
   */
  exports.prototype['user_id'] = undefined;



  return exports;
}));


