/**
 * AI Mastering API
 * This is a AI Mastering API document. You can use the mastering feature of [AI Mastering](https://aimastering.com) through this API.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: aimasteringcom@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Aimastering) {
      root.Aimastering = {};
    }
    root.Aimastering.Mastering = factory(root.Aimastering.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Mastering model module.
   * @module model/Mastering
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Mastering</code>.
   * @alias module:model/Mastering
   * @class
   */
  var exports = function() {
    var _this = this;





























  };

  /**
   * Constructs a <code>Mastering</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Mastering} obj Optional instance to populate.
   * @return {module:model/Mastering} The populated <code>Mastering</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('user_id')) {
        obj['user_id'] = ApiClient.convertToType(data['user_id'], 'Number');
      }
      if (data.hasOwnProperty('input_audio_id')) {
        obj['input_audio_id'] = ApiClient.convertToType(data['input_audio_id'], 'Number');
      }
      if (data.hasOwnProperty('output_audio_id')) {
        obj['output_audio_id'] = ApiClient.convertToType(data['output_audio_id'], 'Number');
      }
      if (data.hasOwnProperty('output_video_id')) {
        obj['output_video_id'] = ApiClient.convertToType(data['output_video_id'], 'Number');
      }
      if (data.hasOwnProperty('reference_audio_id')) {
        obj['reference_audio_id'] = ApiClient.convertToType(data['reference_audio_id'], 'Number');
      }
      if (data.hasOwnProperty('mode')) {
        obj['mode'] = ApiClient.convertToType(data['mode'], 'String');
      }
      if (data.hasOwnProperty('status')) {
        obj['status'] = ApiClient.convertToType(data['status'], 'String');
      }
      if (data.hasOwnProperty('failure_reason')) {
        obj['failure_reason'] = ApiClient.convertToType(data['failure_reason'], 'String');
      }
      if (data.hasOwnProperty('target_loudness')) {
        obj['target_loudness'] = ApiClient.convertToType(data['target_loudness'], 'Number');
      }
      if (data.hasOwnProperty('output_format')) {
        obj['output_format'] = ApiClient.convertToType(data['output_format'], 'String');
      }
      if (data.hasOwnProperty('preset')) {
        obj['preset'] = ApiClient.convertToType(data['preset'], 'String');
      }
      if (data.hasOwnProperty('bit_depth')) {
        obj['bit_depth'] = ApiClient.convertToType(data['bit_depth'], 'Number');
      }
      if (data.hasOwnProperty('sample_rate')) {
        obj['sample_rate'] = ApiClient.convertToType(data['sample_rate'], 'Number');
      }
      if (data.hasOwnProperty('review_comment')) {
        obj['review_comment'] = ApiClient.convertToType(data['review_comment'], 'String');
      }
      if (data.hasOwnProperty('review_score')) {
        obj['review_score'] = ApiClient.convertToType(data['review_score'], 'Number');
      }
      if (data.hasOwnProperty('mastering_matching_level')) {
        obj['mastering_matching_level'] = ApiClient.convertToType(data['mastering_matching_level'], 'Number');
      }
      if (data.hasOwnProperty('progression')) {
        obj['progression'] = ApiClient.convertToType(data['progression'], 'Number');
      }
      if (data.hasOwnProperty('bass_preservation')) {
        obj['bass_preservation'] = ApiClient.convertToType(data['bass_preservation'], 'Boolean');
      }
      if (data.hasOwnProperty('mastering')) {
        obj['mastering'] = ApiClient.convertToType(data['mastering'], 'Boolean');
      }
      if (data.hasOwnProperty('retry_count')) {
        obj['retry_count'] = ApiClient.convertToType(data['retry_count'], 'Number');
      }
      if (data.hasOwnProperty('mastering_reverb')) {
        obj['mastering_reverb'] = ApiClient.convertToType(data['mastering_reverb'], 'Boolean');
      }
      if (data.hasOwnProperty('mastering_reverb_gain')) {
        obj['mastering_reverb_gain'] = ApiClient.convertToType(data['mastering_reverb_gain'], 'Number');
      }
      if (data.hasOwnProperty('low_cut_freq')) {
        obj['low_cut_freq'] = ApiClient.convertToType(data['low_cut_freq'], 'Number');
      }
      if (data.hasOwnProperty('high_cut_freq')) {
        obj['high_cut_freq'] = ApiClient.convertToType(data['high_cut_freq'], 'Number');
      }
      if (data.hasOwnProperty('expire_at')) {
        obj['expire_at'] = ApiClient.convertToType(data['expire_at'], 'Date');
      }
      if (data.hasOwnProperty('created_at')) {
        obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
      }
      if (data.hasOwnProperty('updated_at')) {
        obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
      }
    }
    return obj;
  }

  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {Number} user_id
   */
  exports.prototype['user_id'] = undefined;
  /**
   * @member {Number} input_audio_id
   */
  exports.prototype['input_audio_id'] = undefined;
  /**
   * @member {Number} output_audio_id
   */
  exports.prototype['output_audio_id'] = undefined;
  /**
   * @member {Number} output_video_id
   */
  exports.prototype['output_video_id'] = undefined;
  /**
   * @member {Number} reference_audio_id
   */
  exports.prototype['reference_audio_id'] = undefined;
  /**
   * @member {module:model/Mastering.ModeEnum} mode
   */
  exports.prototype['mode'] = undefined;
  /**
   * @member {module:model/Mastering.StatusEnum} status
   */
  exports.prototype['status'] = undefined;
  /**
   * @member {module:model/Mastering.FailureReasonEnum} failure_reason
   */
  exports.prototype['failure_reason'] = undefined;
  /**
   * @member {Number} target_loudness
   */
  exports.prototype['target_loudness'] = undefined;
  /**
   * @member {module:model/Mastering.OutputFormatEnum} output_format
   */
  exports.prototype['output_format'] = undefined;
  /**
   * @member {module:model/Mastering.PresetEnum} preset
   */
  exports.prototype['preset'] = undefined;
  /**
   * @member {Number} bit_depth
   */
  exports.prototype['bit_depth'] = undefined;
  /**
   * @member {Number} sample_rate
   */
  exports.prototype['sample_rate'] = undefined;
  /**
   * @member {String} review_comment
   */
  exports.prototype['review_comment'] = undefined;
  /**
   * @member {Number} review_score
   */
  exports.prototype['review_score'] = undefined;
  /**
   * @member {Number} mastering_matching_level
   */
  exports.prototype['mastering_matching_level'] = undefined;
  /**
   * @member {Number} progression
   */
  exports.prototype['progression'] = undefined;
  /**
   * @member {Boolean} bass_preservation
   */
  exports.prototype['bass_preservation'] = undefined;
  /**
   * @member {Boolean} mastering
   */
  exports.prototype['mastering'] = undefined;
  /**
   * @member {Number} retry_count
   */
  exports.prototype['retry_count'] = undefined;
  /**
   * @member {Boolean} mastering_reverb
   */
  exports.prototype['mastering_reverb'] = undefined;
  /**
   * @member {Number} mastering_reverb_gain
   */
  exports.prototype['mastering_reverb_gain'] = undefined;
  /**
   * @member {Number} low_cut_freq
   */
  exports.prototype['low_cut_freq'] = undefined;
  /**
   * @member {Number} high_cut_freq
   */
  exports.prototype['high_cut_freq'] = undefined;
  /**
   * @member {Date} expire_at
   */
  exports.prototype['expire_at'] = undefined;
  /**
   * @member {Date} created_at
   */
  exports.prototype['created_at'] = undefined;
  /**
   * @member {Date} updated_at
   */
  exports.prototype['updated_at'] = undefined;


  /**
   * Allowed values for the <code>mode</code> property.
   * @enum {String}
   * @readonly
   */
  exports.ModeEnum = {
    /**
     * value: "default"
     * @const
     */
    "default": "default",
    /**
     * value: "custom"
     * @const
     */
    "custom": "custom",
    /**
     * value: "preset"
     * @const
     */
    "preset": "preset"  };

  /**
   * Allowed values for the <code>status</code> property.
   * @enum {String}
   * @readonly
   */
  exports.StatusEnum = {
    /**
     * value: "waiting"
     * @const
     */
    "waiting": "waiting",
    /**
     * value: "processing"
     * @const
     */
    "processing": "processing",
    /**
     * value: "canceled"
     * @const
     */
    "canceled": "canceled",
    /**
     * value: "failed"
     * @const
     */
    "failed": "failed",
    /**
     * value: "succeeded"
     * @const
     */
    "succeeded": "succeeded"  };

  /**
   * Allowed values for the <code>failure_reason</code> property.
   * @enum {String}
   * @readonly
   */
  exports.FailureReasonEnum = {
    /**
     * value: "unknown"
     * @const
     */
    "unknown": "unknown",
    /**
     * value: "expired"
     * @const
     */
    "expired": "expired",
    /**
     * value: "failed_to_prepare"
     * @const
     */
    "failed_to_prepare": "failed_to_prepare",
    /**
     * value: "job_queue"
     * @const
     */
    "job_queue": "job_queue"  };

  /**
   * Allowed values for the <code>output_format</code> property.
   * @enum {String}
   * @readonly
   */
  exports.OutputFormatEnum = {
    /**
     * value: "wav"
     * @const
     */
    "wav": "wav",
    /**
     * value: "mp3"
     * @const
     */
    "mp3": "mp3"  };

  /**
   * Allowed values for the <code>preset</code> property.
   * @enum {String}
   * @readonly
   */
  exports.PresetEnum = {
    /**
     * value: "general"
     * @const
     */
    "general": "general",
    /**
     * value: "pop"
     * @const
     */
    "pop": "pop",
    /**
     * value: "jazz"
     * @const
     */
    "jazz": "jazz",
    /**
     * value: "classical"
     * @const
     */
    "classical": "classical"  };


  return exports;
}));


