/**
 * AI Mastering API
 * This is a AI Mastering API document. You can use the mastering feature of [AI Mastering](https://aimastering.com) through this API.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@bakuage.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Aimastering) {
      root.Aimastering = {};
    }
    root.Aimastering.Subscription = factory(root.Aimastering.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Subscription model module.
   * @module model/Subscription
   * @version 1.1.0
   */

  /**
   * Constructs a new <code>Subscription</code>.
   * @alias module:model/Subscription
   * @class
   */
  var exports = function() {
    var _this = this;












  };

  /**
   * Constructs a <code>Subscription</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Subscription} obj Optional instance to populate.
   * @return {module:model/Subscription} The populated <code>Subscription</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('user_id')) {
        obj['user_id'] = ApiClient.convertToType(data['user_id'], 'Number');
      }
      if (data.hasOwnProperty('stripe_subscription_id')) {
        obj['stripe_subscription_id'] = ApiClient.convertToType(data['stripe_subscription_id'], 'String');
      }
      if (data.hasOwnProperty('current_period_start_at')) {
        obj['current_period_start_at'] = ApiClient.convertToType(data['current_period_start_at'], 'Date');
      }
      if (data.hasOwnProperty('current_period_end_at')) {
        obj['current_period_end_at'] = ApiClient.convertToType(data['current_period_end_at'], 'Date');
      }
      if (data.hasOwnProperty('canceled')) {
        obj['canceled'] = ApiClient.convertToType(data['canceled'], 'Boolean');
      }
      if (data.hasOwnProperty('cancel_at_period_end')) {
        obj['cancel_at_period_end'] = ApiClient.convertToType(data['cancel_at_period_end'], 'Boolean');
      }
      if (data.hasOwnProperty('trial_end')) {
        obj['trial_end'] = ApiClient.convertToType(data['trial_end'], 'Date');
      }
      if (data.hasOwnProperty('status')) {
        obj['status'] = ApiClient.convertToType(data['status'], 'String');
      }
      if (data.hasOwnProperty('created_at')) {
        obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
      }
      if (data.hasOwnProperty('updated_at')) {
        obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
      }
    }
    return obj;
  }

  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {Number} user_id
   */
  exports.prototype['user_id'] = undefined;
  /**
   * @member {String} stripe_subscription_id
   */
  exports.prototype['stripe_subscription_id'] = undefined;
  /**
   * @member {Date} current_period_start_at
   */
  exports.prototype['current_period_start_at'] = undefined;
  /**
   * @member {Date} current_period_end_at
   */
  exports.prototype['current_period_end_at'] = undefined;
  /**
   * @member {Boolean} canceled
   */
  exports.prototype['canceled'] = undefined;
  /**
   * @member {Boolean} cancel_at_period_end
   */
  exports.prototype['cancel_at_period_end'] = undefined;
  /**
   * @member {Date} trial_end
   */
  exports.prototype['trial_end'] = undefined;
  /**
   * @member {module:model/Subscription.StatusEnum} status
   */
  exports.prototype['status'] = undefined;
  /**
   * @member {Date} created_at
   */
  exports.prototype['created_at'] = undefined;
  /**
   * @member {Date} updated_at
   */
  exports.prototype['updated_at'] = undefined;


  /**
   * Allowed values for the <code>status</code> property.
   * @enum {String}
   * @readonly
   */
  exports.StatusEnum = {
    /**
     * value: "trialing"
     * @const
     */
    "trialing": "trialing",
    /**
     * value: "active"
     * @const
     */
    "active": "active",
    /**
     * value: "past_due"
     * @const
     */
    "past_due": "past_due",
    /**
     * value: "unpaid"
     * @const
     */
    "unpaid": "unpaid",
    /**
     * value: "canceled"
     * @const
     */
    "canceled": "canceled"  };


  return exports;
}));


