/**
 * AI Mastering API
 * This is a AI Mastering API document. You can use the mastering feature of [AI Mastering](https://aimastering.com) through this API.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@bakuage.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Aimastering) {
      root.Aimastering = {};
    }
    root.Aimastering.UserStatistics = factory(root.Aimastering.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The UserStatistics model module.
   * @module model/UserStatistics
   * @version 1.1.0
   */

  /**
   * Constructs a new <code>UserStatistics</code>.
   * @alias module:model/UserStatistics
   * @class
   */
  var exports = function() {
    var _this = this;







  };

  /**
   * Constructs a <code>UserStatistics</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UserStatistics} obj Optional instance to populate.
   * @return {module:model/UserStatistics} The populated <code>UserStatistics</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('registration_invitation_count')) {
        obj['registration_invitation_count'] = ApiClient.convertToType(data['registration_invitation_count'], 'Number');
      }
      if (data.hasOwnProperty('subscription_invitation_count')) {
        obj['subscription_invitation_count'] = ApiClient.convertToType(data['subscription_invitation_count'], 'Number');
      }
      if (data.hasOwnProperty('mastering_count')) {
        obj['mastering_count'] = ApiClient.convertToType(data['mastering_count'], 'Number');
      }
      if (data.hasOwnProperty('monthly_registration_invitation_count')) {
        obj['monthly_registration_invitation_count'] = ApiClient.convertToType(data['monthly_registration_invitation_count'], 'Number');
      }
      if (data.hasOwnProperty('monthly_subscription_invitation_count')) {
        obj['monthly_subscription_invitation_count'] = ApiClient.convertToType(data['monthly_subscription_invitation_count'], 'Number');
      }
      if (data.hasOwnProperty('monthly_mastering_count')) {
        obj['monthly_mastering_count'] = ApiClient.convertToType(data['monthly_mastering_count'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {Number} registration_invitation_count
   */
  exports.prototype['registration_invitation_count'] = undefined;
  /**
   * @member {Number} subscription_invitation_count
   */
  exports.prototype['subscription_invitation_count'] = undefined;
  /**
   * @member {Number} mastering_count
   */
  exports.prototype['mastering_count'] = undefined;
  /**
   * @member {Number} monthly_registration_invitation_count
   */
  exports.prototype['monthly_registration_invitation_count'] = undefined;
  /**
   * @member {Number} monthly_subscription_invitation_count
   */
  exports.prototype['monthly_subscription_invitation_count'] = undefined;
  /**
   * @member {Number} monthly_mastering_count
   */
  exports.prototype['monthly_mastering_count'] = undefined;



  return exports;
}));


