/**
 * AI Mastering API
 * This is a AI Mastering API document. You can use the mastering feature of [AI Mastering](https://aimastering.com) through this API.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: aimasteringcom@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/PaymentCustomer'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/PaymentCustomer'));
  } else {
    // Browser globals (root is window)
    if (!root.Aimastering) {
      root.Aimastering = {};
    }
    root.Aimastering.PaymentCustomerApi = factory(root.Aimastering.ApiClient, root.Aimastering.PaymentCustomer);
  }
}(this, function(ApiClient, PaymentCustomer) {
  'use strict';

  /**
   * PaymentCustomer service.
   * @module api/PaymentCustomerApi
   * @version 1.0.0
   */

  /**
   * Constructs a new PaymentCustomerApi. 
   * @alias module:api/PaymentCustomerApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the getDefaultPaymentCustomer operation.
     * @callback module:api/PaymentCustomerApi~getDefaultPaymentCustomerCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/PaymentCustomer>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get a default payment customer.
     * @param {module:api/PaymentCustomerApi~getDefaultPaymentCustomerCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/PaymentCustomer>}
     */
    this.getDefaultPaymentCustomer = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['bearer'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = [PaymentCustomer];

      return this.apiClient.callApi(
        '/payment_customers/default', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
