/**
 * AI Mastering API
 * This is a AI Mastering API document. You can use the mastering feature of [AI Mastering](https://aimastering.com) through this API.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@bakuage.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Aimastering);
  }
}(this, function(expect, Aimastering) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Aimastering.ExternalSearchResultItunes();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ExternalSearchResultItunes', function() {
    it('should create an instance of ExternalSearchResultItunes', function() {
      // uncomment below and update the code to test ExternalSearchResultItunes
      //var instane = new Aimastering.ExternalSearchResultItunes();
      //expect(instance).to.be.a(Aimastering.ExternalSearchResultItunes);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new Aimastering.ExternalSearchResultItunes();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new Aimastering.ExternalSearchResultItunes();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instane = new Aimastering.ExternalSearchResultItunes();
      //expect(instance).to.be();
    });

    it('should have the property url (base name: "url")', function() {
      // uncomment below and update the code to test the property url
      //var instane = new Aimastering.ExternalSearchResultItunes();
      //expect(instance).to.be();
    });

    it('should have the property thumbnailUrl (base name: "thumbnail_url")', function() {
      // uncomment below and update the code to test the property thumbnailUrl
      //var instane = new Aimastering.ExternalSearchResultItunes();
      //expect(instance).to.be();
    });

    it('should have the property previewUrl (base name: "preview_url")', function() {
      // uncomment below and update the code to test the property previewUrl
      //var instane = new Aimastering.ExternalSearchResultItunes();
      //expect(instance).to.be();
    });

    it('should have the property albumName (base name: "album_name")', function() {
      // uncomment below and update the code to test the property albumName
      //var instane = new Aimastering.ExternalSearchResultItunes();
      //expect(instance).to.be();
    });

    it('should have the property albumUrl (base name: "album_url")', function() {
      // uncomment below and update the code to test the property albumUrl
      //var instane = new Aimastering.ExternalSearchResultItunes();
      //expect(instance).to.be();
    });

    it('should have the property artistName (base name: "artist_name")', function() {
      // uncomment below and update the code to test the property artistName
      //var instane = new Aimastering.ExternalSearchResultItunes();
      //expect(instance).to.be();
    });

    it('should have the property artistUrl (base name: "artist_url")', function() {
      // uncomment below and update the code to test the property artistUrl
      //var instane = new Aimastering.ExternalSearchResultItunes();
      //expect(instance).to.be();
    });

    it('should have the property trackNumber (base name: "track_number")', function() {
      // uncomment below and update the code to test the property trackNumber
      //var instane = new Aimastering.ExternalSearchResultItunes();
      //expect(instance).to.be();
    });

  });

}));
