/**
 * AI Mastering API
 * This is a AI Mastering API document. You can use the mastering feature of [AI Mastering](https://aimastering.com) through this API.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@bakuage.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AccessToken', 'model/AmazonSubscription', 'model/AnonymizedMastering', 'model/Audio', 'model/AudioAnalysis', 'model/AudioDownloadToken', 'model/Config', 'model/ConfigAuth0', 'model/ConfigPaypal', 'model/ConfigStripe', 'model/ConfigVersion', 'model/ExternalSearchResult', 'model/ExternalSearchResultItunes', 'model/ExternalSearchResultYoutube', 'model/GroupBuyStatistics', 'model/JWT', 'model/Kpi', 'model/LibraryAudio', 'model/LibraryAudioAnalysis', 'model/LibraryAudioLike', 'model/Mastering', 'model/Payment', 'model/PaymentCustomer', 'model/Plan', 'model/SpSubscription', 'model/Subscription', 'model/User', 'model/UserStatistics', 'model/Video', 'model/VideoDownloadToken', 'api/AccessTokenApi', 'api/AmazonSubscriptionApi', 'api/AudioApi', 'api/ConfigApi', 'api/ExternalSearchApi', 'api/LibraryAudioApi', 'api/MasteringApi', 'api/PaymentApi', 'api/PaymentCustomerApi', 'api/PlanApi', 'api/SpSubscriptionApi', 'api/StatisticsApi', 'api/SubscriptionApi', 'api/UserApi', 'api/VideoApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/AccessToken'), require('./model/AmazonSubscription'), require('./model/AnonymizedMastering'), require('./model/Audio'), require('./model/AudioAnalysis'), require('./model/AudioDownloadToken'), require('./model/Config'), require('./model/ConfigAuth0'), require('./model/ConfigPaypal'), require('./model/ConfigStripe'), require('./model/ConfigVersion'), require('./model/ExternalSearchResult'), require('./model/ExternalSearchResultItunes'), require('./model/ExternalSearchResultYoutube'), require('./model/GroupBuyStatistics'), require('./model/JWT'), require('./model/Kpi'), require('./model/LibraryAudio'), require('./model/LibraryAudioAnalysis'), require('./model/LibraryAudioLike'), require('./model/Mastering'), require('./model/Payment'), require('./model/PaymentCustomer'), require('./model/Plan'), require('./model/SpSubscription'), require('./model/Subscription'), require('./model/User'), require('./model/UserStatistics'), require('./model/Video'), require('./model/VideoDownloadToken'), require('./api/AccessTokenApi'), require('./api/AmazonSubscriptionApi'), require('./api/AudioApi'), require('./api/ConfigApi'), require('./api/ExternalSearchApi'), require('./api/LibraryAudioApi'), require('./api/MasteringApi'), require('./api/PaymentApi'), require('./api/PaymentCustomerApi'), require('./api/PlanApi'), require('./api/SpSubscriptionApi'), require('./api/StatisticsApi'), require('./api/SubscriptionApi'), require('./api/UserApi'), require('./api/VideoApi'));
  }
}(function(ApiClient, AccessToken, AmazonSubscription, AnonymizedMastering, Audio, AudioAnalysis, AudioDownloadToken, Config, ConfigAuth0, ConfigPaypal, ConfigStripe, ConfigVersion, ExternalSearchResult, ExternalSearchResultItunes, ExternalSearchResultYoutube, GroupBuyStatistics, JWT, Kpi, LibraryAudio, LibraryAudioAnalysis, LibraryAudioLike, Mastering, Payment, PaymentCustomer, Plan, SpSubscription, Subscription, User, UserStatistics, Video, VideoDownloadToken, AccessTokenApi, AmazonSubscriptionApi, AudioApi, ConfigApi, ExternalSearchApi, LibraryAudioApi, MasteringApi, PaymentApi, PaymentCustomerApi, PlanApi, SpSubscriptionApi, StatisticsApi, SubscriptionApi, UserApi, VideoApi) {
  'use strict';

  /**
   * This_is_a_AI_Mastering_API_document__You_can_use_the_mastering_feature_of__AI_Mastering_httpsaimastering_com_through_this_API_.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var Aimastering = require('index'); // See note below*.
   * var xxxSvc = new Aimastering.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new Aimastering.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new Aimastering.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new Aimastering.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 1.0.0
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The AccessToken model constructor.
     * @property {module:model/AccessToken}
     */
    AccessToken: AccessToken,
    /**
     * The AmazonSubscription model constructor.
     * @property {module:model/AmazonSubscription}
     */
    AmazonSubscription: AmazonSubscription,
    /**
     * The AnonymizedMastering model constructor.
     * @property {module:model/AnonymizedMastering}
     */
    AnonymizedMastering: AnonymizedMastering,
    /**
     * The Audio model constructor.
     * @property {module:model/Audio}
     */
    Audio: Audio,
    /**
     * The AudioAnalysis model constructor.
     * @property {module:model/AudioAnalysis}
     */
    AudioAnalysis: AudioAnalysis,
    /**
     * The AudioDownloadToken model constructor.
     * @property {module:model/AudioDownloadToken}
     */
    AudioDownloadToken: AudioDownloadToken,
    /**
     * The Config model constructor.
     * @property {module:model/Config}
     */
    Config: Config,
    /**
     * The ConfigAuth0 model constructor.
     * @property {module:model/ConfigAuth0}
     */
    ConfigAuth0: ConfigAuth0,
    /**
     * The ConfigPaypal model constructor.
     * @property {module:model/ConfigPaypal}
     */
    ConfigPaypal: ConfigPaypal,
    /**
     * The ConfigStripe model constructor.
     * @property {module:model/ConfigStripe}
     */
    ConfigStripe: ConfigStripe,
    /**
     * The ConfigVersion model constructor.
     * @property {module:model/ConfigVersion}
     */
    ConfigVersion: ConfigVersion,
    /**
     * The ExternalSearchResult model constructor.
     * @property {module:model/ExternalSearchResult}
     */
    ExternalSearchResult: ExternalSearchResult,
    /**
     * The ExternalSearchResultItunes model constructor.
     * @property {module:model/ExternalSearchResultItunes}
     */
    ExternalSearchResultItunes: ExternalSearchResultItunes,
    /**
     * The ExternalSearchResultYoutube model constructor.
     * @property {module:model/ExternalSearchResultYoutube}
     */
    ExternalSearchResultYoutube: ExternalSearchResultYoutube,
    /**
     * The GroupBuyStatistics model constructor.
     * @property {module:model/GroupBuyStatistics}
     */
    GroupBuyStatistics: GroupBuyStatistics,
    /**
     * The JWT model constructor.
     * @property {module:model/JWT}
     */
    JWT: JWT,
    /**
     * The Kpi model constructor.
     * @property {module:model/Kpi}
     */
    Kpi: Kpi,
    /**
     * The LibraryAudio model constructor.
     * @property {module:model/LibraryAudio}
     */
    LibraryAudio: LibraryAudio,
    /**
     * The LibraryAudioAnalysis model constructor.
     * @property {module:model/LibraryAudioAnalysis}
     */
    LibraryAudioAnalysis: LibraryAudioAnalysis,
    /**
     * The LibraryAudioLike model constructor.
     * @property {module:model/LibraryAudioLike}
     */
    LibraryAudioLike: LibraryAudioLike,
    /**
     * The Mastering model constructor.
     * @property {module:model/Mastering}
     */
    Mastering: Mastering,
    /**
     * The Payment model constructor.
     * @property {module:model/Payment}
     */
    Payment: Payment,
    /**
     * The PaymentCustomer model constructor.
     * @property {module:model/PaymentCustomer}
     */
    PaymentCustomer: PaymentCustomer,
    /**
     * The Plan model constructor.
     * @property {module:model/Plan}
     */
    Plan: Plan,
    /**
     * The SpSubscription model constructor.
     * @property {module:model/SpSubscription}
     */
    SpSubscription: SpSubscription,
    /**
     * The Subscription model constructor.
     * @property {module:model/Subscription}
     */
    Subscription: Subscription,
    /**
     * The User model constructor.
     * @property {module:model/User}
     */
    User: User,
    /**
     * The UserStatistics model constructor.
     * @property {module:model/UserStatistics}
     */
    UserStatistics: UserStatistics,
    /**
     * The Video model constructor.
     * @property {module:model/Video}
     */
    Video: Video,
    /**
     * The VideoDownloadToken model constructor.
     * @property {module:model/VideoDownloadToken}
     */
    VideoDownloadToken: VideoDownloadToken,
    /**
     * The AccessTokenApi service constructor.
     * @property {module:api/AccessTokenApi}
     */
    AccessTokenApi: AccessTokenApi,
    /**
     * The AmazonSubscriptionApi service constructor.
     * @property {module:api/AmazonSubscriptionApi}
     */
    AmazonSubscriptionApi: AmazonSubscriptionApi,
    /**
     * The AudioApi service constructor.
     * @property {module:api/AudioApi}
     */
    AudioApi: AudioApi,
    /**
     * The ConfigApi service constructor.
     * @property {module:api/ConfigApi}
     */
    ConfigApi: ConfigApi,
    /**
     * The ExternalSearchApi service constructor.
     * @property {module:api/ExternalSearchApi}
     */
    ExternalSearchApi: ExternalSearchApi,
    /**
     * The LibraryAudioApi service constructor.
     * @property {module:api/LibraryAudioApi}
     */
    LibraryAudioApi: LibraryAudioApi,
    /**
     * The MasteringApi service constructor.
     * @property {module:api/MasteringApi}
     */
    MasteringApi: MasteringApi,
    /**
     * The PaymentApi service constructor.
     * @property {module:api/PaymentApi}
     */
    PaymentApi: PaymentApi,
    /**
     * The PaymentCustomerApi service constructor.
     * @property {module:api/PaymentCustomerApi}
     */
    PaymentCustomerApi: PaymentCustomerApi,
    /**
     * The PlanApi service constructor.
     * @property {module:api/PlanApi}
     */
    PlanApi: PlanApi,
    /**
     * The SpSubscriptionApi service constructor.
     * @property {module:api/SpSubscriptionApi}
     */
    SpSubscriptionApi: SpSubscriptionApi,
    /**
     * The StatisticsApi service constructor.
     * @property {module:api/StatisticsApi}
     */
    StatisticsApi: StatisticsApi,
    /**
     * The SubscriptionApi service constructor.
     * @property {module:api/SubscriptionApi}
     */
    SubscriptionApi: SubscriptionApi,
    /**
     * The UserApi service constructor.
     * @property {module:api/UserApi}
     */
    UserApi: UserApi,
    /**
     * The VideoApi service constructor.
     * @property {module:api/VideoApi}
     */
    VideoApi: VideoApi
  };

  return exports;
}));
