/**
 * AI Mastering API
 * This is a AI Mastering API document. You can use the mastering feature of [AI Mastering](https://aimastering.com) through this API.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: aimasteringcom@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Aimastering);
  }
}(this, function(expect, Aimastering) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Aimastering.LibraryAudioApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('LibraryAudioApi', function() {
    describe('createLibraryAudio', function() {
      it('should call createLibraryAudio successfully', function(done) {
        //uncomment below and update the code to test createLibraryAudio
        //instance.createLibraryAudio(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createLibraryAudioLike', function() {
      it('should call createLibraryAudioLike successfully', function(done) {
        //uncomment below and update the code to test createLibraryAudioLike
        //instance.createLibraryAudioLike(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteLibraryAudio', function() {
      it('should call deleteLibraryAudio successfully', function(done) {
        //uncomment below and update the code to test deleteLibraryAudio
        //instance.deleteLibraryAudio(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getLibraryAudio', function() {
      it('should call getLibraryAudio successfully', function(done) {
        //uncomment below and update the code to test getLibraryAudio
        //instance.getLibraryAudio(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getLibraryAudioAnalysis', function() {
      it('should call getLibraryAudioAnalysis successfully', function(done) {
        //uncomment below and update the code to test getLibraryAudioAnalysis
        //instance.getLibraryAudioAnalysis(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listLibraryAudios', function() {
      it('should call listLibraryAudios successfully', function(done) {
        //uncomment below and update the code to test listLibraryAudios
        //instance.listLibraryAudios(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateLibraryAudio', function() {
      it('should call updateLibraryAudio successfully', function(done) {
        //uncomment below and update the code to test updateLibraryAudio
        //instance.updateLibraryAudio(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
